version: "3.3"

services:
  dev:
    ports:
      - 8081:8081
    container_name: hippo-lamdera
    image: hippo-lamdera:dev
    networks:
      - hippo-lamdera-network
    working_dir: /root/code
    volumes:
      - .:/root/code
    command: lamdera live --port 8081

  check:
    image: hippo-lamdera:dev
    networks:
      - hippo-lamdera-network
    working_dir: /root/code
    volumes:
      - .:/root/code
    command: lamdera check

networks:
  hippo-lamdera-network:
    driver: bridge
    ipam:
      driver: default
