version: "3.3"

services:
  bash:
    image: hippo-lamdera:dev
    networks:
      - hippo-lamdera-network
    working_dir: /root/code
    volumes:
      - .:/root/code
    command: bash

  dev:
    ports:
      - 8000:8000
    container_name: hippo-lamdera
    image: hippo-lamdera:dev
    networks:
      - hippo-lamdera-network
    stdin_open: true
    tty: true
    working_dir: /root/code
    volumes:
      - .:/root/code
    command: lamdera live

  check:
    image: hippo-lamdera:dev
    networks:
      - hippo-lamdera-network
    working_dir: /root/code
    volumes:
      - .:/root/code
    command: lamdera check
  
  generate_test_data:
    image: dev-kit:latest
    volumes:
      - .:/home/appuser/workspace
    command: python ./shell-scripts/generate_test_data.py

networks:
  hippo-lamdera-network:
    driver: bridge
    ipam:
      driver: default
